"resources"
{
"cs_norhttower.nav" "file"
"cs_northtower.txt" "file"
"materials/wtc/wtc_tog2.vmt" "file"
"materials/wtc/wtc_tog2.vtf" "file"
"materials/wtc/wtc_decal_light_f1.vmt" "file"
"materials/wtc/wtc_decal_light_f1.vtf" "file"
"materials/wtc/wtc_decal_elevbutu.vmt" "file"
"materials/wtc/wtc_decal_elevbutu.vtf" "file"
"materials/wtc/wtc_decal_elevbutud.vmt" "file"
"materials/wtc/wtc_decal_elevbutud.vtf" "file"
"materials/wtc/wtc_decal_foyerrug.vmt" "file"
"materials/wtc/wtc_decal_foyerrug.vtf" "file"
"materials/wtc/wtc_decal_foyersculpt.vmt" "file"
"materials/wtc/wtc_decal_foyersculpt.vtf" "file"
"materials/wtc/wtc_decal_light_f2.vmt" "file"
"materials/wtc/wtc_decal_light_f2.vtf" "file"
"materials/wtc/wtc_decal_light_i.vmt" "file"
"materials/wtc/wtc_decal_lights_h.vmt" "file"
"materials/wtc/wtc_decal_lights_h.vtf" "file"
"materials/wtc/wtc_decal_lights_v.vmt" "file"
"materials/wtc/wtc_decal_lights_v.vtf" "file"
"materials/wtc/wtc_decal_onewtc.vmt" "file"
"materials/wtc/wtc_decal_onewtc.vtf" "file"
"materials/wtc/wtc_decal_twowtc.vmt" "file"
"materials/wtc/wtc_decal_twowtc.vtf" "file"
}
