name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package maps
        run: ./build.sh

      - name: Upload maps
        uses: actions/upload-artifact@v2.2.1
        with:
          path: dist/

      - name: Deploy tarball
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          TARGET_FOLDER: releases/nightly

      - name: Deploy downloadurl
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: downloadurl
          TARGET_FOLDER: releases/nightly/cstrike