name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package maps
        run: ./build.sh

      - name: Collect Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: dist/maps.tar.xz
          retention-days: 5

      - name: Deploy downloadurl
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: downloadurl
          TARGET_FOLDER: releases/nightly/cstrike
